tests/test_nubank_client.py
Fala galera, adicionei mais dois testes para o client do Nubank. Com isso conseguimos cobrir a lib com testes e seguir no desenvolvimento.
Espero que gostem.
PS-1: Eu acabei não atualizando corretamente minha branch e esse PR trouxe esses commits que já foram mergeados mas que já estão na master do andreroggeri/pynubank.
PS-2: Verifiquei o build do Travis e ele já está executando os testes. Legal né?
=> Adiciona testes para os métodos do client

README.md, pynubank/nubank.py, pynubank/queries/account_balance.gql, pynubank/queries/account_feed.gql, setup.py, tests/test_nubank_client.py
=> feat: Add NuConta support

pynubank/nubank.py, tests/test_nubank_client.py
=> Adicionar endpoint para faturas do cartão

.gitignore, README.md, pynubank/nubank.py, tests/test_nubank_client.py
Este PR resolve #13
Mudei a assinatura das funções para ser mais breve.
Criei um teste de cobertura de código.
Adicionei ao README um exemplo de uso.
Adicionei uma pasta de cache ao .gitignore.
=> Adiciona endpoint para fatura detalhada

README.md
=> Update README.md with warning about account lockout

pynubank/nubank.py, tests/test_nubank_client.py
Criado mais testes para o feed e statements da NuConta.
=> Create more tests for account feed

pynubank/nubank.py
* Adiciona método que consulta a URL `discovery` do nubank
* Atribui o valor da URL `login`para o variável TOKEN_URL
* Troca de `Nubank.TOKEN_URL` para `self.TOKEN_URL` no método `authenticate`
Fix: https://github.com/andreroggeri/pynubank/issues/22
=> Fix login url

requirements-test.txt
=> Switch libraries from python-coveralls to coveralls-python

pynubank/queries/account_feed.gql
=>  Fix GraphQL query to get debit amount

README.md, pynubank/nubank.py, tests/test_nubank_client.py
The refresh_token  is no longer returned by the login API. Closes: #69. Related PR: #64
=> Remove refresh_token auth

README.md, pynubank/nubank.py, requirements.txt, setup.py, tests/test_nubank_client.py
=> Revert qrcode auth

pynubank/nubank.py, pynubank/queries/account_id.gql, pynubank/queries/create_boleto.gql, tests/fixtures/__init__.py, tests/fixtures/create_boleto.py, tests/test_nubank_client.py
=> feat: Add boleto feature

pynubank/nubank.py, pynubank/queries/account_feed.gql, pynubank/queries/create_money_request.gql, tests/fixtures/__init__.py, tests/fixtures/account_statements.py, tests/fixtures/create_money_request.py, tests/test_nubank_client.py
=> feat: Add create_money_request method

.travis.yml, README.md, setup.py
=> Multi python test

pynubank/nubank.py, pynubank/queries/account_feed.gql
Adicionando os valores de Saque e a Tarifa de Saque ao método get_account_statements()
Closes #140
=> Adicionando os valores de Saque e a Tarifa de Saque ao método get_account_statements()

pynubank/queries/account_feed.gql
Resolve amounts with TransferOutReversalEvent type
=> TransferOutReversalEvent Add

setup.py
mocked responses json files missing when installing using setuptools
=> Installing mocked responses json files with pip

pynubank/exception.py, pynubank/nubank.py, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/customer.json, tests/test_nubank_client.py
Adding customer method to retrieve Nubank customer information
=> feat: Add customer method

.gitignore, examples/README.md, examples/pix.md, pynubank/nubank.py, pynubank/queries/create_pix_money_request.gql, pynubank/queries/get_pix_keys.gql, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/customer.json, pynubank/utils/mocked_responses/pix_keys.json, pynubank/utils/mocked_responses/pix_money_request.json, tests/test_nubank_client.py
=> feat: Add Pix QRCode generation

pynubank/nubank.py, setup.py
PR criado para mitigar o issue #195 , o qual é causado pela instabilidade na ordem dos sets criados para suporte a cartões de crédito e débito.
Closes #195
=> Mudança de estrutura de dados para chaves de URL

pynubank/__init__.py, pynubank/utils/discovery.py, pynubank/utils/http.py, tests/test_discovery.py
Testa se a api está disponível para evitar requisições de client quando a api está indisponível
=> feat: Adding api live check

pynubank/nubank.py
Não consegui armazenar o novo refresh token de alguma maneira, então o commit é bem simples apenas retorna o refresh_token após o request de autenticação
=> update: return refresh_token on refresh token authentication

.travis.yml, pynubank/__init__.py, pynubank/nubank.py, pynubank/utils/discovery.py, tests/test_nubank_client.py
=> Fix default parameters

examples/analysis.md
Problems with pd.read_json, changing to pd.DataFrame
=> change to DataFrame, even working in the collab

pynubank/nubank.py, pynubank/utils/parsing.py, tests/test_nubank_client.py, tests/test_parsing.py
Based on #223
Closes: #223
Closes #213
=> feat: Parse Pix transactions

pynubank/nubank.py
Primeiro de tudo, muito obrigado por este projeto!
Adicionar filtro para adquirir os pagamentos feitos no cartão de crédito.
=> Add payments list filter to credit cards

pynubank/utils/parsing.py, tests/test_parsing.py
Corrigindo o Regex, acabei me passando na vez que fiz e ele pegou o  "2021,", porque não especifiquei que era pra pegar com dados obrigatórios após a ","
=> fix: regex filtering empty data after ","

examples/pix.md, pynubank/nubank.py, pynubank/queries/pix_receipt_screen.gql, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/pix_receipt_screen.json, pynubank/utils/mocked_responses/pix_receipt_screen_not_found.json, pynubank/utils/mocked_responses/pix_receipt_screen_without_identifier.json, tests/test_nubank_client.py
=> feat: Add pix qrcode with identifier and fetch pix transaction status

examples/README.md, examples/extract-all-paginated-feed-pages.md, pynubank/nubank.py, pynubank/queries/account_feed_paginated.gql, pynubank/utils/http.py, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/account_feed_paginated.json, pynubank/utils/parsing.py, tests/test_mock_http_client.py, tests/test_parsing.py
Continuação da #301 
Closes: #321 #318 #296 #301 #289
=> Add account feed pagination

pynubank/nubank.py, pynubank/utils/mocked_responses/pix_receipt_screen.json, setup.py, tests/test_nubank_client.py
Esse commit tem como objetivo adicionar um método que procure e obtenha a mensagem enviada via PIX na API do NuBank.
O questionamento foi levantado [aqui nesse issue](https://github.com/andreroggeri/pynubank/issues/319), e esse commit deve solucionar a requisição.
Closes #319 
Signed-off-by: Rodrigo Câmara <rodrigoarenacamara@gmail.com>
=> Adicionando método get_pix_message

pynubank/nubank.py, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/account.json
I could not create the mock file for this so please if anyone could or maybe @andreroggeri :) tnks
the main idea here is to get the current open credit card value
I needed for a personal project and created this methods, worked just fine but I could not create the mock file (the mock system was quite complex)
=> Added Open Credit Card Value

pynubank/nubank.py, pynubank/queries/account_savings.gql, pynubank/utils/mock_http.py, pynubank/utils/mocked_responses/account_savings.json, tests/test_nubank_client.py
Esse commit adiciona as funções requisitadas no issue [#312](https://github.com/andreroggeri/pynubank/issues/312).
=> Adicionando funções para GET do 'dinheiro guardado'
